// Generated by jextract

package org.libtiff;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef int (*TIFFErrorHandlerExtR)(TIFF *, void *, const char *, const char *, va_list)
 * }
 */
public class TIFFErrorHandlerExtR {

    TIFFErrorHandlerExtR() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(MemorySegment _x0, MemorySegment user_data, MemorySegment _x2, MemorySegment _x3, MemorySegment _x4);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        tiffio_h.C_INT,
        tiffio_h.C_POINTER,
        tiffio_h.C_POINTER,
        tiffio_h.C_POINTER,
        tiffio_h.C_POINTER,
        tiffio_h.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = tiffio_h.upcallHandle(TIFFErrorHandlerExtR.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(TIFFErrorHandlerExtR.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment user_data, MemorySegment _x2, MemorySegment _x3, MemorySegment _x4) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, _x0, user_data, _x2, _x3, _x4);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

