// Generated by jextract

package org.libtiff;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     uint32_t uNum;
 *     uint32_t uDenom;
 * }
 * }
 */
public class TIFFRational_t {

    TIFFRational_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        tiffio_h.C_INT.withName("uNum"),
        tiffio_h.C_INT.withName("uDenom")
    ).withName("$anon$266:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt uNum$LAYOUT = (OfInt)$LAYOUT.select(groupElement("uNum"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t uNum
     * }
     */
    public static final OfInt uNum$layout() {
        return uNum$LAYOUT;
    }

    private static final long uNum$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t uNum
     * }
     */
    public static final long uNum$offset() {
        return uNum$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t uNum
     * }
     */
    public static int uNum(MemorySegment struct) {
        return struct.get(uNum$LAYOUT, uNum$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t uNum
     * }
     */
    public static void uNum(MemorySegment struct, int fieldValue) {
        struct.set(uNum$LAYOUT, uNum$OFFSET, fieldValue);
    }

    private static final OfInt uDenom$LAYOUT = (OfInt)$LAYOUT.select(groupElement("uDenom"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t uDenom
     * }
     */
    public static final OfInt uDenom$layout() {
        return uDenom$LAYOUT;
    }

    private static final long uDenom$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t uDenom
     * }
     */
    public static final long uDenom$offset() {
        return uDenom$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t uDenom
     * }
     */
    public static int uDenom(MemorySegment struct) {
        return struct.get(uDenom$LAYOUT, uDenom$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t uDenom
     * }
     */
    public static void uDenom(MemorySegment struct, int fieldValue) {
        struct.set(uDenom$LAYOUT, uDenom$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

