// Generated by jextract

package org.libtiff;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class tiffvers_h {

    tiffvers_h() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();
    static final boolean TRACE_DOWNCALLS = Boolean.getBoolean("jextract.trace.downcalls");

    static void traceDowncall(String name, Object... args) {
         String traceArgs = Arrays.stream(args)
                       .map(Object::toString)
                       .collect(Collectors.joining(", "));
         System.out.printf("%s(%s)\n", name, traceArgs);
    }

    static MemorySegment findOrThrow(String symbol) {
        return SYMBOL_LOOKUP.find(symbol)
            .orElseThrow(() -> new UnsatisfiedLinkError("unresolved symbol: " + symbol));
    }

    static MethodHandle upcallHandle(Class<?> fi, String name, FunctionDescriptor fdesc) {
        try {
            return MethodHandles.lookup().findVirtual(fi, name, fdesc.toMethodType());
        } catch (ReflectiveOperationException ex) {
            throw new AssertionError(ex);
        }
    }

    static MemoryLayout align(MemoryLayout layout, long align) {
        return switch (layout) {
            case PaddingLayout p -> p;
            case ValueLayout v -> v.withByteAlignment(align);
            case GroupLayout g -> {
                MemoryLayout[] alignedMembers = g.memberLayouts().stream()
                        .map(m -> align(m, align)).toArray(MemoryLayout[]::new);
                yield g instanceof StructLayout ?
                        MemoryLayout.structLayout(alignedMembers) : MemoryLayout.unionLayout(alignedMembers);
            }
            case SequenceLayout s -> MemoryLayout.sequenceLayout(s.elementCount(), align(s.elementLayout(), align));
        };
    }

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());

    public static final ValueLayout.OfBoolean C_BOOL = ValueLayout.JAVA_BOOLEAN;
    public static final ValueLayout.OfByte C_CHAR = ValueLayout.JAVA_BYTE;
    public static final ValueLayout.OfShort C_SHORT = ValueLayout.JAVA_SHORT;
    public static final ValueLayout.OfInt C_INT = ValueLayout.JAVA_INT;
    public static final ValueLayout.OfLong C_LONG_LONG = ValueLayout.JAVA_LONG;
    public static final ValueLayout.OfFloat C_FLOAT = ValueLayout.JAVA_FLOAT;
    public static final ValueLayout.OfDouble C_DOUBLE = ValueLayout.JAVA_DOUBLE;
    public static final AddressLayout C_POINTER = ValueLayout.ADDRESS
            .withTargetLayout(MemoryLayout.sequenceLayout(java.lang.Long.MAX_VALUE, JAVA_BYTE));
    public static final ValueLayout.OfLong C_LONG = ValueLayout.JAVA_LONG;
    private static final int TIFFLIB_VERSION = (int)20230908L;
    /**
     * {@snippet lang=c :
     * #define TIFFLIB_VERSION 20230908
     * }
     */
    public static int TIFFLIB_VERSION() {
        return TIFFLIB_VERSION;
    }
    private static final int TIFFLIB_MAJOR_VERSION = (int)4L;
    /**
     * {@snippet lang=c :
     * #define TIFFLIB_MAJOR_VERSION 4
     * }
     */
    public static int TIFFLIB_MAJOR_VERSION() {
        return TIFFLIB_MAJOR_VERSION;
    }
    private static final int TIFFLIB_MINOR_VERSION = (int)6L;
    /**
     * {@snippet lang=c :
     * #define TIFFLIB_MINOR_VERSION 6
     * }
     */
    public static int TIFFLIB_MINOR_VERSION() {
        return TIFFLIB_MINOR_VERSION;
    }
    private static final int TIFFLIB_MICRO_VERSION = (int)0L;
    /**
     * {@snippet lang=c :
     * #define TIFFLIB_MICRO_VERSION 0
     * }
     */
    public static int TIFFLIB_MICRO_VERSION() {
        return TIFFLIB_MICRO_VERSION;
    }
    /**
     * {@snippet lang=c :
     * #define TIFFLIB_VERSION_STR "LIBTIFF, Version 4.6.0
     * Copyright (c) 1988-1996 Sam Leffler
     * Copyright (c) 1991-1996 Silicon Graphics, Inc."
     * }
     */
    public static MemorySegment TIFFLIB_VERSION_STR() {
        class Holder {
            static final MemorySegment TIFFLIB_VERSION_STR
                = tiffvers_h.LIBRARY_ARENA.allocateFrom("LIBTIFF, Version 4.6.0\nCopyright (c) 1988-1996 Sam Leffler\nCopyright (c) 1991-1996 Silicon Graphics, Inc.");
        }
        return Holder.TIFFLIB_VERSION_STR;
    }
    /**
     * {@snippet lang=c :
     * #define TIFFLIB_VERSION_STR_MAJ_MIN_MIC "4.6.0"
     * }
     */
    public static MemorySegment TIFFLIB_VERSION_STR_MAJ_MIN_MIC() {
        class Holder {
            static final MemorySegment TIFFLIB_VERSION_STR_MAJ_MIN_MIC
                = tiffvers_h.LIBRARY_ARENA.allocateFrom("4.6.0");
        }
        return Holder.TIFFLIB_VERSION_STR_MAJ_MIN_MIC;
    }
}

