// Generated by jextract

package org.libtiff;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _TIFFRGBAImage TIFFRGBAImage
 * }
 */
public class TIFFRGBAImage extends _TIFFRGBAImage {

    TIFFRGBAImage() {
        // Should not be called directly
    }
}

